### ISSUE TITLE
Documenation On Compiling This

### ISSUE THREAD

**Issue by kamikazechaser** [Karlheinzniebuhr/Whatsapp-Flooder#1]
Is there a documenation of compiling this to crx

**Comment by Karlheinzniebuhr** [comment]
just add it to Chrome like shown here https://www.youtube.com/watch?v=F1ocns75oKw

**Comment by kamikazechaser** [comment]
Telegram Request: 
Add custom message field...

**Comment by Karlheinzniebuhr** [comment]
Telegram request ? Sorry this one is for Whatsapp only.
If you want to add something feel free to send a PR

**Comment by kamikazechaser** [comment]
I meant the telegram version

**Comment by Karlheinzniebuhr** [comment]
I don't have a telegram version sorry

**Comment by kamikazechaser** [comment]
karlheinzniebuhr.github.io/downloads/Telegram_bots.exe.zip

**Comment by kamikazechaser** [comment]
Isnt that your product?

**Comment by Karlheinzniebuhr** [comment]
It's not my product, a friend made it.

**Comment by kamikazechaser** [comment]
Ok cool
